### ISSUE TITLE
flight.dist_info doesn't work

### ISSUE THREAD

**Issue by Nickduino** [Springvar/home-assistant-flightradar24-card#11]
![image](https://github.com/user-attachments/assets/0f015d67-8b05-410f-a293-eda0df847eca)

This works, though:
`position_status: <div>Position : ${[flight.dist_in_unit + flight.approach_indicator, flight.direction_info].filter((el) => el).join(" • ")}</div>`

![image](https://github.com/user-attachments/assets/73045153-7d13-4cb8-a2e2-dc2c035c10ae)
(I wish I could add a space between the value and the unit, just like you do for speed)

The full yaml in case I missed something

```
type: custom:flightradar24-card
units:
  speed: kmh
radar:
  hide: false
  range: 15
  hide_range: false
  ring_distance: 10
  local_features:
    - type: location
      label: Puy-de-Dôme
      position:
        lat: 45.772449
        lon: 2.964544
    - type: location
      label: Paris
      position:
        lat: 48.860081
        lon: 2.343109
    - type: location
      label: Lyon
      position:
        lat: 45.755061
        lon: 4.837016
    - type: location
      label: Aulhat
      position:
        lat: 45.5370604
        lon: 2.5488797
    - type: runway
      position:
        lat: 45.784821
        lon: 3.150787
      heading: 81
      length: 9885.171
    - type: runway
      position:
        lat: 45.787129
        lon: 3.155251
      heading: 81
      length: 2982.28
    - type: runway
      position:
        lat: 45.781448
        lon: 3.151535
      heading: 7
      length: 2116.14
no_flights_message: Il n'y a pas de vol dans la zone
templates:
  dist_info: ${flight.dist_in_unit ? "Distance : " + flight.dist_in_unit + flight.approach_indicator : undefined}
  aircraft_info: >-
    ${[flight.aircraft_registration, flight.aircraft_model].filter((el) =>
    el).join(" • ")}
  flight_info: >-
    ${[flight.airline_short, flight.flight_number, flight.callsign !==
    flight.flight_number ? flight.callsign : ""].filter((el) => el).join(" • ")}
  origin_info: >-
    ${[flight.airport_origin_city, tpl.departure_info,
    flight.origin_flag].filter((el) => el).join("")}
  destination_info: >-
    ${[flight.airport_destination_city, tpl.arrival_info,
    flight.destination_flag].filter((el) => el).join(" ")}
  route_info: >-
    ${[tpl.origin_info, tpl.destination_info].filter((el) => el).join("&nbsp; →
    &nbsp;")}
  flight_status: >-
    <div>${[tpl.alt_info, tpl.spd_info, tpl.hdg_info].filter((el) => el).join("
    • ")}</div>
  position_status: >-
    <div>${[flight.dist_info, flight.direction_info].filter((el) => el).join(" •
    ")}</div>
  alt_info: >-
    ${flight.alt_in_unit ? "" + flight.alt_in_unit +
    flight.climb_descend_indicator : undefined}
  spd_info: "${flight.spd_in_unit ? \"\" + flight.spd_in_unit : undefined}"
  hdg_info: "${flight.heading ? \"Cap : \" + flight.heading + \"°\" : undefined}"
  proximity_info: >-
    <div style="font-weight: bold; font-style: italic;">${flight.is_approaching
    && flight.ground_speed > 70 && flight.closest_passing_distance < 15 ?
    'Closest Distance: ${Math.round(flight.closest_passing_distance)}
    ${units.distance}, ETA: ${Math.round(flight.eta_to_closest_distance)} min' :
    ""}</div>
```

I also tried with and without defining `dist_info`, to no avail.
