### ISSUE TITLE
Not working v0.0.10 ?¿?

### ISSUE THREAD

**Issue by DoverKan** [Springvar/home-assistant-flightradar24-card#4]
I have performed the installation several times by restarting HA but the card does not appear so that it can be selected and if you create it manually, the error message is: (Cannot read properties of undefined (reading 'ring_distance').

Code for card:

```
type: custom:flightradar24-card
toggles:
  show_on_ground:
    label: Show aircraft on the ground
    default: false
filter:
  - type: OR
    conditions:
      - field: altitude
        comparator: gt
        value: 0
      - defined: show_on_ground
        comparator: eq
        value: true
```
